# When adding a new dependency, Yarn will use an exact version (e.g., 1.2.3)
# instead of a version range (e.g., ^1.2.3).
defaultSemverRangePrefix: ""

# This disables the collection of anonymous usage data by Yarn.
enableTelemetry: false

# This tells Yarn to install dependencies in a node_modules folder,
# which is the standard way for Node.js to resolve modules.
nodeLinker: node-modules

# security: scripts are not enabled by default and required individual activations in package.json
enableScripts: false

# security: NPM package younger than 3 days won't be considered for installation
npmMinimalAgeGate: 4320
