name: Publish @filigran/chatbot to NPM (one-shot)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Enable Corepack
        run: npm install -g corepack
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build @filigran/chatbot
        run: yarn workspace @filigran/chatbot run build
      - name: Publish @filigran/chatbot to NPM
        working-directory: ./packages/filigran-chatbot
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
